language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: releases
  api_key:
    secure: VR3WQ8iRxCNKqFK/2HnNiph+JfHW3+9X3v5C89VVlvsY+Q6aT2VyLgiO+fVHJFamxq79m6khRIlfSroQ6HO29zpKivIR9wMqKUhcku1Er326iJPAo6fkwdOUym9Wg5SqWxGqEzkAVwrz8H+DX620vMOJSPeou7DZjCsWli+cCvFyftKezhamqPL4/v1NAjcHHZMTOb1CcKpSpv2oBS5uoZpvN21/fvvLkQeQhdcwD4kgaHkh6ch8FpG3q/ERtpxZc8UL+hXHuTHzzPyU8ph3qlJaOnaR3aCYE4cH5UadgxcaQH0vb0uKOo3PO0LUsBY0odcoU5CIBJ6IHqqZpXAbCDcNLoBx4FLcp+shH70UkrG6zrnEgw1zOr2kbsRZCfBrN7s/OW4VXFp5vFNjBmhKTD84uPKo9H7LEXbt6hsjLjIrtpyU+hKUwHXS0KkcuiHQeMw8YFYsTfayVLgU0v7tPdLlTAm1yFeJkp0PuuD+Mb1G26K1K78Ukduzzctr+jo5Yy5rjchPw3h5Ubmct4NUpsBwsMWiLyL0xFQYBIsSt1ju/4Z8MwjhgUJjsNH+bqdVmrgLQ5uY/xO7SMaYxqj9Gs5BV2EkkYoxg7RPfVYsF7ZSMaM4eQiN221TzdiiYO3H/MJSLfrVM1eXPRb4ZraKu+t5WE5+NHqJSdEuRGiW2XA=
    file: "./target/release/hugo_to_json"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false