language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
deploy:
  provider: releases
  api_key:
    secure: X7qYG3ov8I5StK6ugJ5/jzXo0Q+DEQuS2++1sIA0mEm7M5F42CT0cOgw0m5fB8WvxIlGv15hTI397qu5n97gfRnmGp6Cn/fjaplOa9CAUMX7zHtNULa4b4DvYoHGEs9Fz54L3A0kYPDGGCduKe2QtY+GoKtLrvpBvvlsuYBQTUjluoUnTLcca7qMcYOsvRmxyNOCf18y5SOGzJJXf4QSrG+2RhFDGNuFwHkLwxKPuIQGJSZ/CxrWJJzoSRfaw1xqjIrvNcJ8afx3rA+TpvgRSw9AIPz9vZ9/3RbbiF8hS5JBvB4my0QdVCdZfnP6gj79EWL2p8ZG0EsnlbVtRvmOOOd0pk2pxxlfxIM+7iL3tLswABXYdzMqCIGh3HW9Ygpx5Y2Ijaj4YG8WpWv1NPwZxGvJ/ZbJ0e47uuOycP+YZ0pwfqp9Bysp7HJPHb0JtTxb1Df0BUHt8e01fDMcrWkjB/tf+RahtIRZTBpl5z/XMK20YphtTwqPpIIPoVPwf5bpStyWzItDoBN9d1JPFNhRMO7hm0UZCU+0ZGIAFqhujgWtR0xsybHke4flIIfwXidUmJMGtU6aYkQcwHeJjNTAplY3MKInrXn4Z35GDjoa7X9nxQFslS1Aht1wIIL79BJN5lxORQdYns3evsVMAfUi3N3H7zdtKov6EioQgXMZmOE=
  file: "./target/release/hugo_to_json"
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false