[package]
name = "hugo_lunr"
version = "0.1.0"
authors = ["Arran France <arranf@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.4.10"
walkdir = "2"
serde_json = "1.0"
serde = "1.0.84"
serde_derive = "1.0"