version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test
      - run:
          name: Confirm location and files
          command: pwd && ls ./target/release
      - persist_to_workspace:
          root: ./target/release
          paths:
            - hugo_to_json
      - store_artifacts:
            path: ./target/release/hugo_to_json
            destination: artifacts
     

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Debug /tmp/artifacts"
          command: ls /tmp/artifacts
      - run:
          name: "Chmod hugo_to_json"
          command: chmod +x /tmp/artifacts/hugo_to_json
      - run:
          name: "Check version"
          command: /tmp/artifacts/hugo_to_json --version
      - run:
          name: "Check version again"
          command: VERSION=$(/tmp/artifacts/hugo_to_json --version) echo ${VERSION}
      - run:
          name: "Publish Release on GitHub"
          command:
            VERSION=$(/tmp/artifacts/hugo_to_json --version) \
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/artifacts/hugo_to_json
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/