version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test
      - run:
          name: Confirm location and files
          command: pwd && ls ./target/release
      - persist_to_workspace:
          root: ./target/release
          paths:
            - hugo_to_json
      - store_artifacts:
            path: ./target/release/hugo_to_json
            destination: artifacts


  publish-github-release:
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Copy to local folder"
          command: cp /tmp/artifacts/hugo_to_json .
      - run:
          name: "Check version"
          command: ./hugo_to_json --version
      - run:
          name: "Get GHR"
          command: go get github.com/tcnksm/ghr
      - run:
          name: "Publish Release on GitHub"
          command:
            export VERSION=$(./hugo_to_json --version | cut -d " " -f 4) && /go/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./hugo_to_json
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/